Repository nyu-mll/jiant, pull requests merged in 2020-01, with the labels that each got.

#986 Remove code initializing optimizer and scheduler fields in task_info
  jiant/trainer.py
Labels: cleanup

#987 Remove MaskedMultiHeadSelfAttention and MaskedStackedSelfAttentionEncoder
  jiant/modules/masked_stacked_attn_layer.py
  jiant/utils/utils.py
Labels: cleanup

#988 Cleanup/readability changes in trainer.py
  jiant/trainer.py
Labels: cleanup

#991 Minor change to maintain sorted order of tasks to reduce variation in logs
  jiant/models.py
Labels: cleanup

#994 Add docstrings and type hints in setup and preprocessing code
  jiant/__main__.py
  jiant/preprocess.py
  jiant/utils/config.py
  jiant/utils/options.py
Labels: cleanup, documentation

#990 Update to transformers 2.3.0 & Add ALBERT
  README.md
  environment.yml
  gcp/config/jiant_paths.sh
  gcp/kubernetes/templates/jiant_env.libsonnet
  gcp/kubernetes/templates/run_batch.jsonnet
  gcp/set_up_workstation.sh
  jiant/config/defaults.conf
  jiant/config/examples/stilts_example.conf
  jiant/config/superglue_bert.conf
  jiant/huggingface_transformers_interface/__init__.py
  jiant/huggingface_transformers_interface/modules.py
  jiant/models.py
  jiant/modules/sentence_encoder.py
  jiant/preprocess.py
  jiant/pytorch_transformers_interface/__init__.py
  jiant/tasks/qa.py
  jiant/tasks/tasks.py
  jiant/utils/retokenize.py
  jiant/utils/tokenizers.py
  jiant/utils/utils.py
  scripts/ccg/align_tags_to_bert.py
  scripts/demo.with_docker.sh
  scripts/edgeprobing/exp_fns.sh
  setup.py
  tests/test_huggingface_transformers_interface.py
  tests/test_retokenize.py
  tutorials/setup_tutorial.md
Labels: 0.x.0 release on fix
